Add streaming support
koopjs/koop-core pull request #142
Opened 2021-07-16 13:41 UTC by andrewctate

Adds support for provider plugins using NodeJS streams instead of JSON to pass data to the output plugins (issue https://github.com/koopjs/koop-core/issues/141).

Caching doesn't make sense in this case, so the `pullStream` method is quite simple.

2021-07-16 13:50 UTC, haoliangyu requested changes

2021-07-16 13:50 UTC, haoliangyu commented on lib/provider-registration/create-model.js
> +        callback(null, providerStream)
You need to add a try...catch here to make sure any error is sent back to the callback. See an example at the pull() function.

Yeah, it sucks to have promise and callback in the same place.

2021-07-16 17:23 UTC, haoliangyu approved these changes
LGTM

2021-07-16 17:34 UTC, merged

2021-07-19 14:22 UTC, rgwozdz commented
If this is ready for release, you can follow steps at https://github.com/koopjs/koop-core/blob/master/RELEASE.md.